### ISSUE TITLE
Metrical inscription note to explain symbols

### ISSUE THREAD

**Issue by emylonas** [MedCyprus/MedCyprusEFES#12]
In metrical inscriptions, have a small note to the reader explaining the meaning of the vertical bars an line numbers. Lineation is metrical.

**Comment by emylonas** [comment]
check https://iospe.kcl.ac.uk/5.238.html
there is a separate tab for verse display vs. actual painted lineation

**Comment by gabrielbodard** [comment]
Tab for verse view is implemented.

Explanation of vertical lines in verse view is still open: assigned to @emylonas

**Comment by emylonas** [comment]
editionStruct MedCyprus in the XSL. 
But what should the text say?

**Comment by gabrielbodard** [comment]
Closed with commit 93ad3996988c38cf1feddecc93673d2a6d60fbb0
