### ISSUE TITLE
Locations-display of Greek name of monuments on EFES

### ISSUE THREAD

**Issue by mparani70** [MedCyprus/MedCyprusEFES#25]
@gabrielbodard @emylonas 

In locations.xml, the Greek name of the monument is included, as well as alternative English names when available. These are not displayed on EFES. Can this be rectified, especially with regards to the Greek name?

**Comment by emylonas** [comment]
put all place names after the first one, in a row with semicolons. In parentheses, after the heading. Should be clearly distinct

**Comment by emylonas** [comment]
Clarification  - all alternate names? English and Greek? 
I have made the 1st Greek name appear after the title, and added some basic formatting.  At the moment, the index only takes into account the first English name and the first Greek name. It's possible to modify the indexing so all the `<placeName>` values are indexed, and displayed below the main title.

**Comment by emylonas** [comment]
fixed with a29ad040dd2c7fbcad1df17ddc0ea38ec56a380e but pending discussion about adding other names
