### ISSUE TITLE
Implement mini-apparatus beneath edition

### ISSUE THREAD

**Issue by gabrielbodard** [MedCyprus/MedCyprusEFES#3]
The mini-apparatus should only capture:

1. sic and corr
2. keep sic in text (no brackets)
3. put corr in apparatus
4. this does NOT apply to reg and orig

**Comment by gabrielbodard** [comment]
from guidelines:

“Internal” apparatus: Spelling mistakes/phonetic spellings etc. in the text (marked as <choice><sic>ΜΑΡΗΑ</sic><corr>ΜΑΡΙΑ</corr></choice>). The “sic” version will appear in the text, as normal. The “corr” version will appear beneath the text, in the form:
1. reg. ΜΑΡΙΑ

**Comment by TheocharisPetrou** [comment]
> from guidelines:
> 
> “Internal” apparatus: Spelling mistakes/phonetic spellings etc. in the text (marked as ΜΑΡΗΑΜΑΡΙΑ). The “sic” version will appear in the text, as normal. The “corr” version will appear beneath the text, in the form:
> 
> 1. reg. ΜΑΡΙΑ

**Comment by TheocharisPetrou** [comment]
> from guidelines:
> 
> “Internal” apparatus: Spelling mistakes/phonetic spellings etc. in the text (marked as ΜΑΡΗΑΜΑΡΙΑ). The “sic” version will appear in the text, as normal. The “corr” version will appear beneath the text, in the form:
> 
> 1. reg. ΜΑΡΙΑ

Gabby how the internal apparatus' process going? Did it sorted?

**Comment by TheocharisPetrou** [comment]
@gabrielbodard @emylonas 

Dear Gabby and Elli,
Happy new year with health and prosperity!!
I would like to ask you if the internal apparatus' issue was sorted in order to start adding it in xml?

**Comment by gabrielbodard** [comment]
It's not implemented in EFES now (sorry!) but that's no reason to start tagging these details correctly in the EpiDoc. Do you have a question about how to tag something?

**Comment by TheocharisPetrou** [comment]
@gabrielbodard 
So if I understand correctly, at this moment we can't proceed with the apparatus until this formula is sorted?

**Comment by TheocharisPetrou** [comment]
@gabrielbodard 
Thank you very much Gabby for the clarification. I will make some examples and show them to you at Tuesday's zoom meeting.

**Comment by gabrielbodard** [comment]
First implementation of this issue at commit [d141c9207ccdbec40dcc608ac14d25902c58f8a4](https://github.com/MedCyprus/MedCyprusEFES/commit/d141c9207ccdbec40dcc608ac14d25902c58f8a4)

**Comment by gabrielbodard** [comment]
Closed and approved.
