### ISSUE TITLE
fix issue of article in w-tag

### ISSUE THREAD

**Issue by gabrielbodard** [MedCyprus/MedCyprusEFES#4]
There are several instances of Ὁ ἅγιος being tagged inside the `<w>` tag, which is messing up the Greek words index.

When you have `<w lemma="ἅγιος">Ὁ ἅγιος</w>`

it should be changed to `Ὁ <w lemma="ἅγιος">ἅγιος</w>`

If there are a lot of these to do by hand, feel free to comment on this ticket asking for help automating the fix, and assign it to Gabby or Elli.

**Comment by TheocharisPetrou** [comment]
fixed!!
